---
title: "Neural-Network-based State Estimation: The Effect of Pseudo-Measurements"
author:
  - "Andrea Bragantini"
  - "Davide Baroli"
  - "Andres Felipe Posada-Moreno"
  - "Andrea Benigni"
date: "2021-06-01"
categories: [paper-conference]
description: "Abordando el problema de estimación de estado en sistemas de potencia usando modelos de aprendizaje profundo."
doi: "10.1109/ISIE45552.2021.9576442"
publication-venue: "2021 IEEE 30th International Symposium on Industrial Electronics (ISIE)"
external-url: "https://ieeexplore.ieee.org/document/9576442"
---

## Resumen

Este trabajo busca contribuir al esfuerzo de investigación actual de explotar modelos de aprendizaje profundo para abordar el problema de estimación de estado en sistemas de potencia. En esta contribución, proponemos primero una metodología para generar conjuntos de datos cuando hay pocas mediciones disponibles. El cuerpo principal del trabajo investiga el diseño de redes neuronales artificiales con un estudio extensivo sobre la capa de entrada, que juega un papel crucial en la robustez del estimador. El objetivo es comparar el rendimiento entre modelos que usan pseudo-mediciones adicionales en la entrada y aquellos que no. Los resultados de simulación realizados en el sistema IEEE de 95 buses y una red de prueba de bajo voltaje respaldan las conclusiones del marco propuesto.

## Cita

```bibtex
@inproceedings{bragantini2021neuralnetworkbased,
 author = {Bragantini, Andrea and Baroli, Davide and Posada-Moreno, Andres Felipe and Benigni, Andrea},
 booktitle = {2021 IEEE 30th International Symposium on Industrial Electronics (ISIE)},
 date = {2021-06},
 doi = {10.1109/ISIE45552.2021.9576442},
 pages = {1--6},
 title = {Neural-Network-based State Estimation: The Effect of Pseudo-Measurements},
 url = {https://ieeexplore.ieee.org/document/9576442}
}
```
