---
title: "Objectifying Machine Setup and Parameter Selection in Expert Knowledge Dependent Industries Using Invertible Neural Networks"
author:
  - "Kai Müller"
  - "Andrés Posada-Moreno"
  - "Lukas Pelzer"
  - "Thomas Gries"
date: "2023-01-01"
categories: [paper-conference]
description: "Using invertible neural networks and expert knowledge for parameter prediction in industrial applications."
doi: "10.1007/978-3-031-18326-3_29"
publication-venue: "FAIM 2022 / Flexible Automation and Intelligent Manufacturing (Springer, Lecture Notes in Mechanical Engineering)"
---

## Abstract

The textile industry is one of the oldest and largest industries in the world. The fields of application for textile products are diverse. Although the technologies for manufacturing textiles are extensively researched, the industry is still highly dependent on expert knowledge. To date, manual process- and machine adjustments and quality control are the norms rather than the exception. Heat setting is used in the process chain to dissolve or selectively introduce tensions from the weaving or knitting process and to prepare the products for digital printing. The correct setting of the machine depends on a large number of different materials-, processes- & environmental parameters. For each product, the machine has to be set up again by an experienced textile engineer. To ease the training for new workers and shorten the machine setting process, this study aims to use machine learning to facilitate and objectify the setting of the heat-setting process. Machine parameters are generated using an invertible neural network (INN) based on pre-defined target parameters. The results can be used to identify trends in machine settings and respond accordingly. Thus, a reduction of machine setting time could be realized.

## Citation

```bibtex
@inproceedings{muller2023objectifying,
 author = {Müller, Kai and Posada-Moreno, Andrés and Pelzer, Lukas and Gries, Thomas},
 booktitle = {Flexible Automation and Intelligent Manufacturing: The Human-Data-Technology Nexus},
 date = {2023},
 doi = {10.1007/978-3-031-18326-3_29},
 pages = {293--300},
 publisher = {Springer International Publishing},
 series = {Lecture Notes in Mechanical Engineering},
 title = {Objectifying Machine Setup and Parameter Selection in Expert Knowledge Dependent Industries Using Invertible Neural Networks}
}
```

## Related Projects

- [Internet of Production](/projects/iop/)
