---
title: "ECLAD: Extracting Concepts with Local Aggregated Descriptors"
author:
  - "Andrés Felipe Posada-Moreno"
  - "Nikita Surya"
  - "Sebastian Trimpe"
date: "2023-11-22"
categories: [journal-article]
description: "A novel method for automatic concept extraction and localization based on representations obtained through pixel-wise aggregations of CNN activation maps."
doi: "10.1016/j.patcog.2023.110146"
publication-venue: "Pattern Recognition"
external-url: "https://www.sciencedirect.com/science/article/pii/S0031320323008439"
featured: true
---

## Abstract

Convolutional neural networks (CNNs) are increasingly being used in critical systems, where robustness and alignment are crucial. In this context, the field of explainable artificial intelligence has proposed the generation of high-level explanations of the prediction process of CNNs through concept extraction. While these methods can detect whether or not a concept is present in an image, they are unable to determine its location. What is more, a fair comparison of such approaches is difficult due to a lack of proper validation procedures. To address these issues, we propose a novel method for automatic concept extraction and localization based on representations obtained through pixel-wise aggregations of CNN activation maps. Further, we introduce a process for the quantitative comparison and validation of concept-extraction techniques based on synthetic datasets with pixel-wise annotations of their main components, mitigating possible confirmation biases induced by human visual inspection. Extensive experimentation on both synthetic and real-world datasets demonstrates that our method outperforms state-of-the-art alternatives.

## Citation

```bibtex
@article{posada-moreno2023eclad,
 author = {Posada-Moreno, Andrés Felipe and Surya, Nikita and Trimpe, Sebastian},
 date = {2023-11-22},
 doi = {10.1016/j.patcog.2023.110146},
 issn = {0031-3203},
 journaltitle = {Pattern Recognition},
 volume = {147},
 pages = {110146},
 keywords = {Concept extraction, Convolutional neural networks, Explainable artificial intelligence},
 title = {ECLAD: Extracting Concepts with Local Aggregated Descriptors},
 url = {https://www.sciencedirect.com/science/article/pii/S0031320323008439}
}
```

## Related Projects

- [eXplainable Artificial Intelligence](/projects/xai/)
- [Internet of Production](/projects/iop/)
